### PR TITLE
Fix collidePointArc and update minified version

### LINKED ISSUE #8: collidePointArc method is not included in minified version

### PR DESCRIPTION
**Pull request by davidgranstrom**
Looks like `angleBetween` was recently updated in p5.js to an be [an instance method](https://github.com/processing/p5.js/pull/1950) and `p5.Vector.angleBetween` now seems to be undefined. I ran into this issue when trying to use the collidePointArc method of this library.

I've tested it locally and it is working, but someone should probably double check that the math is still correct before merging.

Closes #8

### CODE REVIEW

**Comment by bmoren** [comment]
@ognjenvucko can you check this out?

**Comment by ognjenvucko** [comment]
@bmoren yes ofc :) today or tomorrow latest.

**Comment by bmoren** [comment]
thank you!

**Comment by ognjenvucko** [comment]
@bmoren @davidgranstrom Yes, ```angleBetween``` has become instance method as of [this ](https://github.com/processing/p5.js/commit/73a403ce3f9257cf1c90631da3b9af1f65340b0d) commit.
All fine, we should merge this :)

**Comment by bmoren** [comment]
thank you @davidgranstrom && @ognjenvucko!

**Pull request merged**
